# n = (input('Digite um valor: '))
# print(n.isupper())

n = input('Digite algo: ')
print('É um número? ', n.isnumeric())
print('É uma letra? ', n.isalpha())
print('É um alfanumérico? ', n.isalnum())
print('Está em maiúscula? ', n.isupper())
print('Está em minúscula? ', n.islower())
# print(n.isascii())
# print(n.isdecimal())
# print(n.isdigit())
# print(n.isidentifier())
# print(n.isprintable())
# print(n.isspace())
# print(n.istitle())
