nome = input('Digite seu nome: ')
sn = input('Digite seu sobrenome: ')
c = input('Digite seu curso: ')
p = input('Digite seu semestre: ')
s = str(input('Digite a matéria: '))
n1 = float(input('Digite sua 1ª nota: '))
n2 = float(input('Digite sua 2ª nota: '))
n3 = float(input('Digite sua 3ª nota: '))
n4 = float(input('Digite sua 4ª nota: '))
n5 = float(input('Digite sua 5ª nota: '))
n6 = float(input('Digite sua 6ª nota: '))
m = (n1*2+n2*2+n3*2.5+n4*1+n5*1+n6*1.5)/10
print(f'Seja bem-vinda, {nome} {sn}!')
print(f'De acordo com as notas avaliadas, sua média final do {p} semestre de {s} será {m:.3f}. \nAproveite as férias com o seu gatito lindo e maravilhoso =D ')
